package by.epamtc.coffee_machine.controller;

public enum CommandName {
	SELECT_POPULAR_DRINKS, REGISTRATION, CHANGE_LANGUAGE, LOGIN, LOG_OUT, VIEW_MENU, VIEW_PRODUCT, VIEW_PRODUCT_EDIT,
	EDIT_PRODUCT, MAKE_ORDER, NO_SUCH_COMMAND
}
