-- MySQL Script generated by MySQL Workbench
-- Thu Oct 21 21:42:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffee_machine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coffee_machine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffee_machine` DEFAULT CHARACTER SET utf8 ;
USE `coffee_machine` ;

-- -----------------------------------------------------
-- Table `coffee_machine`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`accounts` (
  `account_id` BIGINT NOT NULL AUTO_INCREMENT,
  `balance` INT NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`bonus_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`bonus_accounts` (
  `bonus_account_id` BIGINT NOT NULL AUTO_INCREMENT,
  `balance` INT NULL DEFAULT NULL,
  PRIMARY KEY (`bonus_account_id`),
  UNIQUE INDEX `bonus_account_id_UNIQUE` (`bonus_account_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`drinks` (
  `drink_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `image_path` VARCHAR(150) NULL DEFAULT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(350) NULL DEFAULT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`drink_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `drink_id_UNIQUE` (`drink_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coffee_machine`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`ingredients` (
  `ingredient_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `current_amount` INT NULL DEFAULT NULL,
  `image_path` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `ingredient_id_UNIQUE` (`ingredient_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`drink_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`drink_ingredients` (
  `drink_id` BIGINT NOT NULL,
  `ingredient_id` BIGINT NOT NULL,
  `ingredient_amount` INT NOT NULL,
  `is_optional` TINYINT NOT NULL,
  PRIMARY KEY (`drink_id`, `ingredient_id`),
  INDEX `drink_id_idx` (`drink_id` ASC) VISIBLE,
  INDEX `ingredient_id_idx` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `drink_ingredients_drink_id`
    FOREIGN KEY (`drink_id`)
    REFERENCES `coffee_machine`.`drinks` (`drink_id`),
  CONSTRAINT `ingredient_id`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `coffee_machine`.`ingredients` (`ingredient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coffee_machine`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`roles` (
  `role_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `role_id` BIGINT NOT NULL DEFAULT '2',
  `bonus_account_id` BIGINT NOT NULL,
  `account_id` BIGINT NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `bonus_account_id_UNIQUE` (`bonus_account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_user_bonus_account1_idx` (`bonus_account_id` ASC) VISIBLE,
  INDEX `fk_user_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `coffee_machine`.`accounts` (`account_id`),
  CONSTRAINT `bonus_account_id`
    FOREIGN KEY (`bonus_account_id`)
    REFERENCES `coffee_machine`.`bonus_accounts` (`bonus_account_id`),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `coffee_machine`.`roles` (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`feedbacks` (
  `comment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `drink_id` BIGINT NOT NULL,
  `comment_message` VARCHAR(300) NOT NULL,
  `rating` INT NOT NULL,
  `date_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`comment_id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `comments_drink_id_idx` (`drink_id` ASC) VISIBLE,
  INDEX `comments_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `comments_drink_id`
    FOREIGN KEY (`drink_id`)
    REFERENCES `coffee_machine`.`drinks` (`drink_id`),
  CONSTRAINT `comments_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee_machine`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`orders` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `date_time` TIMESTAMP NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'created',
  `cost` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) VISIBLE,
  INDEX `orders_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `coffee_machine`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `coffee_machine`.`order_drinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coffee_machine`.`order_drinks` (
  `order_id` BIGINT NOT NULL,
  `drink_id` BIGINT NOT NULL,
  `drink_count` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `drink_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `drink_id_idx` (`drink_id` ASC) VISIBLE,
  CONSTRAINT `drink_id`
    FOREIGN KEY (`drink_id`)
    REFERENCES `coffee_machine`.`drinks` (`drink_id`),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `coffee_machine`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
